spring:
  application:
    name: gateway
  profiles:
    active: dev
#  redisson:
#        address: 127.0.0.1:6379
#        timeout: 3000
#        database: 0
#        pool:
#          max-active: 20
#          max-idle: 10
#          max-wait: 3000
#          min-idle: 4
server:
  port: 8081
